name: terraform apply

on:
  pull_request:
    branches:
      - master
    types: [closed]
    paths:
      - terraform/**

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup terraform
        uses: hashicorp/setup-terraform@v2

      - name: configure GCP credentials
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/489282523838/locations/global/workloadIdentityPools/github-actions/providers/github-actions-provider'
          service_account: 'github-actions@prism-prod-372103.iam.gserviceaccount.com'

      - name: setup tfcmt
        env:
          TFCMT_VERSION: v4.3.0
        run: |
          wget "https://github.com/suzuki-shunsuke/tfcmt/releases/download/${TFCMT_VERSION}/tfcmt_linux_amd64.tar.gz" -O /tmp/tfcmt.tar.gz
          tar xzf /tmp/tfcmt.tar.gz -C /tmp
          mv /tmp/tfcmt /usr/local/bin

      - run: terraform init
        working-directory: terraform

      - name: terraform apply
        working-directory: terraform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tfcmt apply -- terraform apply -auto-approve